### ISSUE TITLE
Broken After Mistlands update

### ISSUE THREAD

**Issue by KneveTheKnight** [nopetrides/modding#1]
Mod no longer works with Mistlands update. Just letting you know and can freely delete this or I will delete it myself when it is updated for Mistlands. An example is I get a stream of error codes constantly when the game is launched and the mod is on, Unable to place items while the mod is running, unable to use CropUtils mod can pick in the area but unable to place.

**Comment by irischman** [comment]
Same issue.  Hopefully it can get an update as it's a great mod.

**Comment by KneveTheKnight** [comment]
Looks like they updated it within the last 24 hours so I am closing it as fixed for Mistlands!

**Comment by nopetrides** [comment]
Thanks for the heads up, and thanks for closing it. Looks like I need to configure my notification settings!
