### ISSUE TITLE
Patch 0.219.16 Broke CropUtils

### ISSUE THREAD

**Issue by technospice** [nopetrides/modding#11]
I just realized there was a small patch today and I think it broke your mod. I can no longer plant anything with it. I'm wondering if this change from the patch notes may have broken it? 

* World modifier “No Build Cost” no longer allows food to be placed freely, this is now part of the “No Craft Cost” world modifier

- I've not made any changes to the default config. When I hold Alt now, it only shows 2 crops but won't let me plant when clicked.
- When I'm NOT over soil, it shows the red indicators for the full line. If I then move my mouse over tilled soil areas, it gets screwy and starts placing red-indicated crops in random patterns over the soil.

I look forward to this being resolved! This is a fantastic mod that lets me get a lot of chores done during nighttimes in game.

![flaxmod](https://github.com/user-attachments/assets/d648cb67-2396-432b-9064-a18f4430e1da)

**Comment by Rutes** [comment]
jumping in for visibility - I'm also experiencing this!

**Comment by nopetrides** [comment]
Thanks for the heads up!

Mod version 1.5.2 appears to work again on latest.

Good luck with your crops!
