### ISSUE TITLE
Where is the config?

### ISSUE THREAD

**Issue by swatsqad** [nopetrides/modding#2]
Where is it? what are default mappings?

**Comment by pjotrpottervogel** [comment]
do you have installed all requirements? i think you maybe missed:  https://valheim.thunderstore.io/package/NoPetRides/NoPetRides_ModUtils/

**Comment by swatsqad** [comment]
Installed via Thunderstore with those dependencies, so shouldn't be it. In the config editor I only see BepInEx/config/BepInEx.cfg as a configurable, and no cfg's in the local files as far as I can see :/

**Comment by pjotrpottervogel** [comment]
check if you have Crop_Utils.dll and NPR_valheim_ModUtils.dll in the BepInEx/plugins dir. Those Modmanagers fail sometimes.

**Comment by nopetrides** [comment]
Hi!
Thanks for checking out the mod.

The default mappings are the "left alt key" and the "z" key. Alt is for pickup and both Alt and Z are used for the planting mod in various combinations (depending on the order you press them in.) I'll add these to the Readme.

For editing the configs, have you launched the game after installing the mod?
BepInEx config files aren't generated until first time launch with the mod successfully loaded.
Then they should be in the folder Valheim\BepInEx\config, or in the profile's BepInEx\config in the case of installing through Thunderstore
