### ISSUE TITLE
Broken placement on Patch 0.217.14 – Hildir's request

### ISSUE THREAD

**Issue by serpi90** [nopetrides/modding#6]
Trying to place either line or radial only plants the first one and this stack trace happens:

```text
[Error  : Unity Log] MissingFieldException: Field 'PlayerProfile/PlayerStats.m_builds' not found.
Stack trace:
Crop_Utils.PlantingUtil.UpdatePlacementPostfix (Player __instance, System.Boolean takeInput, System.Single dt) (at <e9c3e8592782483d924c7a5629ca61c0>:0)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

**Comment by serpi90** [comment]
Afaik, https://github.com/Xeio/MassFarming/pull/17 should fix this.
Also https://github.com/Xeio/MassFarming/commit/6298988921e7a852d7fa2c95b777c3dc0b8f3e98

**Comment by nopetrides** [comment]
Ah, thanks for letting me know. 
I haven't done a rebuild of the mod for Hildir's Request, but it shouldn't be a difficult fix.
I'll try to find some time to put out an update. and close this when done.

**Comment by nopetrides** [comment]
Updated with new publicized assemblies. Had to update mod util as well.
Tested and working as did previously. Cheers.
